from pydantic import BaseModel
from typing import Optional

class ChatRequest(BaseModel):
    # User session generated by frontend when starting a new chat
    # (will be saved to DB to allow the user to continue old conversations)
    session_id: str
    user_message: str
    league_id: Optional[str] = None

class ChatSession(BaseModel):
    session_id: str
    previous_openai_response_id: Optional[str] = None

class AssistantResponse(BaseModel):
    assistant_response_text: str
    response_id: str